import type { CultureId, LocalizationKey } from '../src/contracts/core';
import type { NamePartDefinition, NamePartId, NamingRuleDefinition, NamingRuleId } from '../src/contracts/character/names';
import { textKeyFor, type Authored, type AuthoredDomain, type AuthoredText } from './authoring';

// Entries are [stable ID, Chinese spelling, English spelling]. Editing a translation must not change its ID.
// Authored whole given names; never random character/syllable concatenation.
const catalogs = [
  {
    "culture": "yunhua",
    "family": [
      [
        "chen",
        "陳",
        "Chen"
      ],
      [
        "he",
        "何",
        "He"
      ],
      [
        "du",
        "杜",
        "Du"
      ],
      [
        "wei",
        "魏",
        "Wei"
      ],
      [
        "lin",
        "林",
        "Lin"
      ],
      [
        "zhou",
        "周",
        "Zhou"
      ],
      [
        "zhao",
        "趙",
        "Zhao"
      ],
      [
        "feng",
        "馮",
        "Feng"
      ],
      [
        "liang",
        "梁",
        "Liang"
      ],
      [
        "song",
        "宋",
        "Song"
      ],
      [
        "zheng",
        "鄭",
        "Zheng"
      ],
      [
        "luo",
        "羅",
        "Luo"
      ]
    ],
    "male": [
      [
        "yue",
        "岳",
        "Yue"
      ],
      [
        "cheng",
        "成",
        "Cheng"
      ],
      [
        "jing",
        "敬",
        "Jing"
      ],
      [
        "ping",
        "平",
        "Ping"
      ],
      [
        "yong",
        "勇",
        "Yong"
      ],
      [
        "wenxiu",
        "文修",
        "Wenxiu"
      ],
      [
        "shikang",
        "世康",
        "Shikang"
      ],
      [
        "boliang",
        "伯良",
        "Boliang"
      ],
      [
        "zhiyuan",
        "志遠",
        "Zhiyuan"
      ],
      [
        "huairen",
        "懷仁",
        "Huairen"
      ],
      [
        "demao",
        "德茂",
        "Demao"
      ],
      [
        "yongnian",
        "永年",
        "Yongnian"
      ],
      [
        "xiuming",
        "修明",
        "Xiuming"
      ],
      [
        "zhongan",
        "仲安",
        "Zhongan"
      ],
      [
        "ziqian",
        "子謙",
        "Ziqian"
      ],
      [
        "dayou",
        "大有",
        "Dayou"
      ]
    ],
    "female": [
      [
        "xiu",
        "秀",
        "Xiu"
      ],
      [
        "min",
        "敏",
        "Min"
      ],
      [
        "rong",
        "蓉",
        "Rong"
      ],
      [
        "lan",
        "蘭",
        "Lan"
      ],
      [
        "zhen",
        "珍",
        "Zhen"
      ],
      [
        "yufen",
        "玉芬",
        "Yufen"
      ],
      [
        "huiru",
        "惠如",
        "Huiru"
      ],
      [
        "chunyan",
        "春燕",
        "Chunyan"
      ],
      [
        "suqin",
        "素琴",
        "Suqin"
      ],
      [
        "wanru",
        "婉如",
        "Wanru"
      ],
      [
        "lijun",
        "麗君",
        "Lijun"
      ],
      [
        "peiwen",
        "佩文",
        "Peiwen"
      ],
      [
        "jingyi",
        "靜宜",
        "Jingyi"
      ],
      [
        "qiurong",
        "秋容",
        "Qiurong"
      ],
      [
        "xiuyun",
        "秀雲",
        "Xiuyun"
      ],
      [
        "shuhua",
        "淑華",
        "Shuhua"
      ]
    ],
    "format": {
      "zh-Hant": "{family}{given}",
      "en": "{family} {given}"
    }
  },
  {
    "culture": "vildun",
    "family": [
      [
        "hervik",
        "赫爾維",
        "Hervik"
      ],
      [
        "skarn",
        "斯卡恩",
        "Skarn"
      ],
      [
        "valden",
        "瓦爾登",
        "Valden"
      ],
      [
        "brek",
        "布雷克",
        "Brek"
      ],
      [
        "holt",
        "霍爾特",
        "Holt"
      ],
      [
        "lind",
        "林德",
        "Lind"
      ],
      [
        "ask",
        "阿斯克",
        "Ask"
      ],
      [
        "sten",
        "斯滕",
        "Sten"
      ]
    ],
    "male": [
      [
        "torven",
        "托文",
        "Torven"
      ],
      [
        "hald",
        "哈爾德",
        "Hald"
      ],
      [
        "sigvar",
        "西格瓦",
        "Sigvar"
      ],
      [
        "rik",
        "里克",
        "Rik"
      ],
      [
        "arne",
        "阿恩",
        "Arne"
      ],
      [
        "erik",
        "埃里克",
        "Erik"
      ],
      [
        "odd",
        "奧德",
        "Odd"
      ],
      [
        "bryn",
        "布林",
        "Bryn"
      ],
      [
        "gunnar",
        "古納",
        "Gunnar"
      ],
      [
        "svein",
        "斯韋恩",
        "Svein"
      ],
      [
        "ivar",
        "伊瓦",
        "Ivar"
      ],
      [
        "leif",
        "勒夫",
        "Leif"
      ]
    ],
    "female": [
      [
        "signa",
        "希格娜",
        "Signa"
      ],
      [
        "inge",
        "英格",
        "Inge"
      ],
      [
        "asta",
        "阿斯妲",
        "Asta"
      ],
      [
        "helga",
        "赫爾嘉",
        "Helga"
      ],
      [
        "hilda",
        "希爾妲",
        "Hilda"
      ],
      [
        "frida",
        "芙麗妲",
        "Frida"
      ],
      [
        "solvi",
        "索爾薇",
        "Solvi"
      ],
      [
        "gudrun",
        "古德倫",
        "Gudrun"
      ],
      [
        "tyra",
        "泰拉",
        "Tyra"
      ],
      [
        "una",
        "烏娜",
        "Una"
      ],
      [
        "rivna",
        "里芙娜",
        "Rivna"
      ],
      [
        "ilsa",
        "伊爾莎",
        "Ilsa"
      ]
    ],
    "format": {
      "zh-Hant": "{given}・{family}",
      "en": "{given} {family}"
    }
  },
  {
    "culture": "aurelien",
    "family": [
      [
        "veyne",
        "維恩",
        "Veyne"
      ],
      [
        "morant",
        "莫朗",
        "Morant"
      ],
      [
        "duval",
        "杜瓦爾",
        "Duval"
      ],
      [
        "bell",
        "貝爾",
        "Bell"
      ],
      [
        "maret",
        "馬雷",
        "Maret"
      ],
      [
        "lowell",
        "洛威爾",
        "Lowell"
      ],
      [
        "cairn",
        "凱恩",
        "Cairn"
      ],
      [
        "vidal",
        "維達爾",
        "Vidal"
      ]
    ],
    "male": [
      [
        "mathis",
        "馬提斯",
        "Mathis"
      ],
      [
        "edmund",
        "艾德蒙",
        "Edmund"
      ],
      [
        "olivier",
        "奧利維",
        "Olivier"
      ],
      [
        "felix",
        "費利克斯",
        "Felix"
      ],
      [
        "remy",
        "雷米",
        "Remy"
      ],
      [
        "hugo",
        "雨果",
        "Hugo"
      ],
      [
        "adrian",
        "阿德里安",
        "Adrian"
      ],
      [
        "nicolas",
        "尼可拉",
        "Nicolas"
      ],
      [
        "simon",
        "西蒙",
        "Simon"
      ],
      [
        "emile",
        "艾米爾",
        "Emile"
      ],
      [
        "leon",
        "萊昂",
        "Leon"
      ],
      [
        "vincent",
        "文森",
        "Vincent"
      ]
    ],
    "female": [
      [
        "aline",
        "艾琳",
        "Aline"
      ],
      [
        "claire",
        "克蕾兒",
        "Claire"
      ],
      [
        "margot",
        "瑪格特",
        "Margot"
      ],
      [
        "cecile",
        "瑟西爾",
        "Cecile"
      ],
      [
        "rose",
        "蘿絲",
        "Rose"
      ],
      [
        "adele",
        "艾黛兒",
        "Adele"
      ],
      [
        "isabelle",
        "伊莎貝爾",
        "Isabelle"
      ],
      [
        "estelle",
        "艾絲黛爾",
        "Estelle"
      ],
      [
        "louise",
        "露易絲",
        "Louise"
      ],
      [
        "viviane",
        "薇薇安",
        "Viviane"
      ],
      [
        "sophie",
        "蘇菲",
        "Sophie"
      ],
      [
        "marianne",
        "瑪莉安",
        "Marianne"
      ]
    ],
    "format": {
      "zh-Hant": "{given}・{family}",
      "en": "{given} {family}"
    }
  },
  {
    "culture": "safir",
    "family": [
      [
        "haddad",
        "哈達德",
        "Haddad"
      ],
      [
        "mansur",
        "曼蘇爾",
        "Mansur"
      ],
      [
        "najjar",
        "納賈爾",
        "Najjar"
      ],
      [
        "sabah",
        "薩巴赫",
        "Sabah"
      ],
      [
        "hakim",
        "哈基姆",
        "Hakim"
      ],
      [
        "rashid",
        "拉希德",
        "Rashid"
      ],
      [
        "khalil",
        "哈利勒",
        "Khalil"
      ],
      [
        "nasser",
        "納賽爾",
        "Nasser"
      ]
    ],
    "male": [
      [
        "nadim",
        "納迪姆",
        "Nadim"
      ],
      [
        "hasan",
        "哈桑",
        "Hasan"
      ],
      [
        "rafiq",
        "拉菲克",
        "Rafiq"
      ],
      [
        "adil",
        "阿迪爾",
        "Adil"
      ],
      [
        "bashir",
        "巴希爾",
        "Bashir"
      ],
      [
        "hamid",
        "哈米德",
        "Hamid"
      ],
      [
        "ilyas",
        "伊利亞斯",
        "Ilyas"
      ],
      [
        "jamil",
        "賈米爾",
        "Jamil"
      ],
      [
        "munir",
        "穆尼爾",
        "Munir"
      ],
      [
        "nabil",
        "納比爾",
        "Nabil"
      ],
      [
        "omar",
        "奧馬爾",
        "Omar"
      ],
      [
        "salim",
        "薩利姆",
        "Salim"
      ]
    ],
    "female": [
      [
        "samira",
        "莎米拉",
        "Samira"
      ],
      [
        "amina",
        "阿米娜",
        "Amina"
      ],
      [
        "hana",
        "哈娜",
        "Hana"
      ],
      [
        "iman",
        "伊曼",
        "Iman"
      ],
      [
        "jamila",
        "賈米拉",
        "Jamila"
      ],
      [
        "lina",
        "莉娜",
        "Lina"
      ],
      [
        "muna",
        "穆娜",
        "Muna"
      ],
      [
        "nura",
        "努拉",
        "Nura"
      ],
      [
        "rania",
        "拉妮雅",
        "Rania"
      ],
      [
        "salma",
        "薩爾瑪",
        "Salma"
      ],
      [
        "soraya",
        "索拉雅",
        "Soraya"
      ],
      [
        "yara",
        "雅拉",
        "Yara"
      ]
    ],
    "format": {
      "zh-Hant": "{given}・{family}",
      "en": "{given} {family}"
    }
  }
] as const;

function namingDomain(culture: typeof catalogs[number]): AuthoredDomain {
  const cultureId = `culture.${culture.culture}` as CultureId;
  const definitions: (Authored<NamePartDefinition> | Authored<NamingRuleDefinition>)[] = [];
  const texts: AuthoredText[] = [];
  const parts = (usage: 'family' | 'male' | 'female', names: readonly (readonly [string, string, string])[]) => names.map(([keyId, zh, en]) => {
    const id = `character-name-part.${culture.culture}.${usage}.${keyId}` as NamePartId;
    const key = textKeyFor(id);
    definitions.push({ id, kind: 'character-name-part', cultureId, usage, display: { nameRef: { key: key as LocalizationKey } } });
    texts.push({ key, name: { 'zh-Hant': zh, en } });
    return id;
  });
  const familyIds = parts('family', culture.family);
  const maleGivenIds = parts('male', culture.male);
  const femaleGivenIds = parts('female', culture.female);
  const id = `character-naming-rule.${culture.culture}.standard` as NamingRuleId;
  const key = textKeyFor(id);
  definitions.push({ id, kind: 'character-naming-rule', cultureId, familyIds, maleGivenIds, femaleGivenIds,
    reservedNames: culture.culture === 'yunhua' ? [{ familyId: 'character-name-part.yunhua.family.wei' as NamePartId, givenId: 'character-name-part.yunhua.male.cheng' as NamePartId }] : [], display: { nameRef: { key: key as LocalizationKey } } });
  texts.push({ key, name: culture.format });
  return { domain: `names-${culture.culture}`, definitions, texts };
}
export const yunhuaNamesDomain = namingDomain(catalogs[0]);
export const worldNamesDomains = catalogs.slice(1).map(namingDomain);
